resolver: nightly-2017-08-15

packages:
- clash-prelude
- clash-lib
- clash-ghc
- testsuite

extra-deps:
- ghc-tcplugins-extra-0.2.1
- ghc-typelits-extra-0.2.3
- ghc-typelits-knownnat-0.3
- ghc-typelits-natnormalise-0.5.3
- uu-interleaved-0.2.0.0
- uu-parsinglib-2.9.1.1
